### ISSUE TITLE
Zero Error but Still Not Working

### ISSUE THREAD

**Issue by alpakbaci** [muskie82/MonoGS#105]
Hi,

I successfully completed the installation on Ubuntu 20.04 WSL without any errors. The GUI opens directly without any issues, but the map is not rendered correctly. I have attached an image below.

My graphics card is a GTX 3070. Could this be the cause of the problem?

I really need help thanks in advance!

<img width="1403" alt="alp3" src="https://github.com/muskie82/MonoGS/assets/115162350/04aa05ca-ea84-424a-9d58-d362de40e56c">

**Comment by MrVladimirLiu** [comment]
It seems wsl can't run this project correctly. I faced the same problem, the thread stuck in dead loop after Initialized map. I had build a docker image but it did't make sense, too.

**Comment by MrVladimirLiu** [comment]
> It seems wsl can't run this project correctly. I faced the same problem, the thread stuck in dead loop after Initialized map. I had build a docker image but it did't make sense, too.

I copy the same image to a linux server and it works well.

**Comment by alpakbaci** [comment]
![sonuc](https://github.com/user-attachments/assets/c609ce90-4d62-4511-8f97-9e895b2d3b19)
![sonuc2](https://github.com/user-attachments/assets/e481b7d7-0ddf-4dc7-88e4-a64327fc7770)

After a while ı got these results but after this i have a new error about matrix singularity again. Any idea of this situation?

**Comment by alpakbaci** [comment]
I changed my operating system from Windows to Linux and my problems were solved. Pytorch works with some problems on Windows

**Comment by FraDePace** [comment]
@hnglp Hi, were you then able to run it with WSL?

**Comment by alpakbaci** [comment]
> @hnglp Hi, were you then able to run it with WSL?

No, since I could not solve the matrix singularity problem with WSL, I was able to run the project by changing my operating system to Linux.
