### ISSUE TITLE
The FPS of the dev.speedup branch

### ISSUE THREAD

**Issue by Chensiyu00** [muskie82/MonoGS#109]
Thanks for your great work!

I have tested the speedup branch on 4080. I find that the branch can achieve almost the same result compared with the origin code. But it only achieve 2FPS on fr3_office which should be 10FPS on 4090 as you say in the Readme. I don't think the card would cause such a big gap.

<img width="528" alt="d67d0fa564cabf40265ec1ecb9f78ed" src="https://github.com/muskie82/MonoGS/assets/88935871/bdee62c9-08d8-47ec-b7fd-b789756c321c">

Do I have any errors in running this code?

Thanks for your help in advance.

**Comment by berniel** [comment]
@Chensiyu00 Hi Chen! I've encountered the same problem and achieves 3.4 FPS on a 3090 GPU. Have you got any solutions for that? Thanks!
