### ISSUE TITLE
How to save the 3DGS result 

### ISSUE THREAD

**Issue by mingyangpeng** [muskie82/MonoGS#11]
Hi, thanks for your work! I ran the code, but not found the result of 3DGS, How to save and show it again?

result blow:
.
├── config.yml
├── plot
├── point_cloud
└── psnr

**Comment by muskie82** [comment]
Hi,
Can you check the issue #3?
Gaussians are saved as .ply file in point_cloud and can be visualised by the standard viewer.

**Comment by mingyangpeng** [comment]
great，thank you!
