### ISSUE TITLE
AttributeError: 'Run' object has no attribute '_telemetry_obj'

### ISSUE THREAD

**Issue by Niamh5163** [muskie82/MonoGS#130]
Hello，everyone.I would like to ask how to solve the error AttributeError: 'Run' object has no attribute '_telemetry_obj', after that when I use this command pip show wandb to view the wandb information, it shows that my version of wandb is 0.17.6, what's wrong with that! What's wrong with that?

**Comment by zuoweic** [comment]
[see.](https://github.com/muskie82/MonoGS/issues/126)

**Comment by Niamh5163** [comment]
> [see.](https://github.com/muskie82/MonoGS/issues/126)

yeah，I found that too,and have solved it.But I have a new error.
