### ISSUE TITLE
error:qt.qpa.plugin: Could not load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by Niamh5163** [muskie82/MonoGS#131]
Hi all, I am having the following problem while running the program:
```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/yjj/anaconda3/envs/MonoGS/lib/python3.7/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.
```
I'd like to ask for a more robust solution, thank you very much!

**Comment by zuoweic** [comment]
pip install opencv-python==4.1.1.26
pip install opencv-contrib-python==4.1.1.26 
i met the same issue and i just fixed it !  It works for me !

**Comment by Niamh5163** [comment]
> pip install opencv-python==4.1.1.26 pip install opencv-contrib-python==4.1.1.26 i met the same issue and i just fixed it ! It works for me !

Wow , I solved the problem based on the information you provided, thank you so much, you are awesome!

**Comment by JzHuai0108** [comment]
In the end, [this post](https://github.com/NVlabs/instant-ngp/discussions/300) works for me.
To quote the solution
```
pip uninstall opencv-python
pip install opencv-python-headless
```
