### ISSUE TITLE
question about camera pose optimization

### ISSUE THREAD

**Issue by Torment123** [muskie82/MonoGS#157]
Hi, I have a question about the initialization of camera poses, in line 121 of slam_frontend.py, it shows that the poses are initialized with the ground truth poses extracted from the dataset, I'm a bit confused here, because based on my understanding the goal of camera optimization is to the ground truth pose of the views through reconstruction based on equation 7 of the paper. If that's the case, why is it appropriate to initialize the viewpoints with ground truth poses? This might be my mistake here since I'm new to SLAM.

**Comment by victkk** [comment]
> Hi, I have a question about the initialization of camera poses, in line 121 of slam_frontend.py, it shows that the poses are initialized with the ground truth poses extracted from the dataset, I'm a bit confused here, because based on my understanding the goal of camera optimization is to the ground truth pose of the views through reconstruction based on equation 7 of the paper. If that's the case, why is it appropriate to initialize the viewpoints with ground truth poses? This might be my mistake here since I'm new to SLAM.

The function is only called for the first frame or when the SLAM system lose track completely(which will then start a new map). It's basically just setting the coordinates.

**Comment by Torment123** [comment]
> > Hi, I have a question about the initialization of camera poses, in line 121 of slam_frontend.py, it shows that the poses are initialized with the ground truth poses extracted from the dataset, I'm a bit confused here, because based on my understanding the goal of camera optimization is to the ground truth pose of the views through reconstruction based on equation 7 of the paper. If that's the case, why is it appropriate to initialize the viewpoints with ground truth poses? This might be my mistake here since I'm new to SLAM.
> 
> The function is only called for the first frame or when the SLAM system lose track completely(which will then start a new map). It's basically just setting the coordinates.

Got it, thanks for replying
