### ISSUE TITLE
Why there is no f_rest property in the ply file?

### ISSUE THREAD

**Issue by NithinJangid** [muskie82/MonoGS#17]
I’ve been working with the generated PLY files and have observed a few issues that I’d like to bring to your attention.

Firstly, I noticed that the generated PLY files lack the f_rest property. This is unlike the original Gaussian splatting PLY files which do include this property. Could you please explain why this discrepancy exists?

Secondly, I’ve found that the quality of the rendered images is not up to par. The images appear to be of poor quality. Could you provide some insight into why this might be happening?

**Comment by muskie82** [comment]
Hi,

1. f_rest is parameters about spherical harmonics. By default, we don't use SH (sh_degree=0) and it does not contain f_rest.

2. We're not sure which methods you're comparing against on which dataset. Can you share the example of rendered images?

**Comment by HerrSchnapps** [comment]
> 我一直在处理生成的 PLY 文件，并发现了一些问题，希望引起您的注意。
> 
> 首先，我注意到生成的 PLY 文件缺少 f_rest 属性。这与原始的高斯分布 PLY 文件不同，后者包含此属性。您能解释一下为什么存在这种差异吗？
> 
> 其次，我发现渲染图像的质量不太理想。图像质量似乎很差。您能解释一下为什么会出现这种情况吗？

Did you solve the rendering problem? I met it as well, the quality of rendering result is poor.
