### ISSUE TITLE
ValueError:Unable to determine Axes to steal space for Colorbar. Either provide the *cax* argument to use as the Axes for the Colorbar, provide the *ax* argument to steal space from it, or add *mappable* to an Axes.

### ISSUE THREAD

**Issue by libaiwanovo** [muskie82/MonoGS#18]
Thank you very much for your excellent work.When I run the TUM dataset,An issue always arises.
How can I resolve this issue?Looking forward to your response, thank you.

![Screenshot 2024-03-12 14:24:24](https://github.com/muskie82/MonoGS/assets/153749298/0f4ce79a-618c-4bcc-b0ab-4dab5a8de045)

**Comment by muskie82** [comment]
Hi,
Can you try downgrading matplotlib?
`pip install matplotlib==3.5.3`

**Comment by libaiwanovo** [comment]
> 嗨，您可以尝试降级 matplotlib 吗？ `pip install matplotlib==3.5.3`

Thank you very much, you have solved my problem！
