### ISSUE TITLE
Upload to a server through my PC

### ISSUE THREAD

**Issue by LoganCome** [muskie82/MonoGS#2]
Due to limited computing power of my PC, I am unable to perform this on-board training. 
I attempt to connect the Realsense camera to my PC and upload in real-time to a server I leased. 
Both my PC and server have public IPs. Could you please advise on how I can achieve this?

**Comment by muskie82** [comment]
Hi,

Realsense API supports image stream over network, so it should be do able. 
For a client-server communication example, refer to [EtherSense on GitHub](https://github.com/krejov100/EtherSense), which demonstrates communication via Ethernet. The wireless should also be doable in similar way... at least I have a similar experience of streaming images via ROS in my previous projects. 

Accordingly, you'll need to modify the image grabber in [our realsense data loader](https://github.com/muskie82/MonoGS/blob/main/utils/dataset.py#L427).

Note that our GUI will run in server side (where training is running). So if you want to visualise the trained data on the client side, you'll need to develop a client-side GUI. Also, the server side needs to send the trained data or renderings to the client-side GUI for visualization.
