### ISSUE TITLE
How to View Result After SLAM

### ISSUE THREAD

**Issue by Buffyqsf** [muskie82/MonoGS#21]
Thanks for your outstanding work!
I have a remote computer with GPU 3090 but without a graphical interface. I got results on that (a point_cloud.ply), and I'm wondering if there is a way that I can view the results locally on my own computer with GPU, using your GUI code. 
But I didn't find any readme about that,  can you provide a simple guide?

**Comment by rmurai0610** [comment]
Hi, we don't have an option to show point cloud using our GUI offline, but you can try the following:
https://github.com/muskie82/MonoGS/issues/3#issuecomment-1979159083

It should display the Gaussian in a browser even if it doesn't have a dedicated GPU.
