### ISSUE TITLE
how can i run it with a RGB-D camera?

### ISSUE THREAD

**Issue by YZWYD** [muskie82/MonoGS#22]
Hello, first of all, thank you for open-sourcing such excellent work. I have a seemingly silly question: How can I use an RGB-D camera and your open-source code to achieve the effects shown in your demo videos?

**Comment by muskie82** [comment]
Thank you for your interest in our work.

- To try rgb-d mode on dataset, just follow the readme.
The commands are 
```
bash scripts/download_tum.sh
python slam.py --config configs/rgbd/tum/fr3_office.yaml
```

- Our live demo with realsense in the video is done with monocular mode.
To try rgb-d mode on realsense live stream, need to change the [sensor type in config file](https://github.com/muskie82/MonoGS/blob/main/configs/live/realsense.yaml#L11) to "rgbd" and add few lines of code in [realsense data loader](https://github.com/muskie82/MonoGS/blob/main/utils/dataset.py#L469) to read depth images.
