### ISSUE TITLE
Environment configuration issue

### ISSUE THREAD

**Issue by nc-thu** [muskie82/MonoGS#25]
An error message during the installation process indicates that pip tried to install the submodules/simple-knn directory as a Python package, but because there was neither a setup.py file nor a pyproject.toml file in this directory, the installation failed.
I checked under ./simple-knn, there is no file

**Comment by muskie82** [comment]
Hi,

I think you just forgot to clone submodules, please check out the issue #8 .

As written in readme, you need to clone the repo with the following command
```git clone https://github.com/muskie82/MonoGS.git --recursive```

Thanks
