### ISSUE TITLE
Camera Tracking result on Replica for Monocular SLAM Results

### ISSUE THREAD

**Issue by 8pterosaur** [muskie82/MonoGS#28]
Hello, the paper shows the results of the RGB-D SLAM on the Replica datasets. 
However, I obtained Monocular SLAM tracking results by adjusting the configuration file. 
For example, on room0 it's about **4cm**, I don't know where I went wrong and the result is unexpected.

Therefore, can you provide the complete evaluation results or guide us on how to adjust configuration file to get correct results.

Thx so much

**Comment by rmurai0610** [comment]
Hi, 
The Replica dataset contains many rotational motions, which is challenging for monocular SLAM.
We didn't have much time, and monocular Replica is out of scope for our work as is (and not included in the paper). 
That said, if you are interested, you can probably tweak the hyperparameters to get better performance - maybe with more mapping iterations in a single process mode or adjusting the keyframing parameter/strategy.

**Comment by 8pterosaur** [comment]
thx, I will try

**Comment by czeyveli1** [comment]
Could you explain how did you add the depth dataset and set the configuration file? I try to do a denoising process to the depth dataset, but I cannot run RGBD SLAM. I couldn't see the depth dataset on the GUI and the system doesnt work..

**Comment by suvzzc** [comment]
> Hello, the paper shows the results of the RGB-D SLAM on the Replica datasets. However, I obtained Monocular SLAM tracking results by adjusting the configuration file. For example, on room0 it's about **4cm**, I don't know where I went wrong and the result is unexpected.
> 
> Therefore, can you provide the complete evaluation results or guide us on how to adjust configuration file to get correct results.
> 
> Thx so much



> Hello, the paper shows the results of the RGB-D SLAM on the Replica datasets. However, I obtained Monocular SLAM tracking results by adjusting the configuration file. For example, on room0 it's about **4cm**, I don't know where I went wrong and the result is unexpected.
> 
> Therefore, can you provide the complete evaluation results or guide us on how to adjust configuration file to get correct results.
> 
> Thx so much



> Hello, the paper shows the results of the RGB-D SLAM on the Replica datasets. However, I obtained Monocular SLAM tracking results by adjusting the configuration file. For example, on room0 it's about **4cm**, I don't know where I went wrong and the result is unexpected.
> 
> Therefore, can you provide the complete evaluation results or guide us on how to adjust configuration file to get correct results.
> 
> Thx so much
Hi, can you tell me what configuration parameters you have adjusted?

**Comment by suvzzc** [comment]
> Hello, the paper shows the results of the RGB-D SLAM on the Replica datasets. However, I obtained Monocular SLAM tracking results by adjusting the configuration file. For example, on room0 it's about **4cm**, I don't know where I went wrong and the result is unexpected.
> 
> Therefore, can you provide the complete evaluation results or guide us on how to adjust configuration file to get correct results.
> 
> Thx so much



> Hello, the paper shows the results of the RGB-D SLAM on the Replica datasets. However, I obtained Monocular SLAM tracking results by adjusting the configuration file. For example, on room0 it's about **4cm**, I don't know where I went wrong and the result is unexpected.
> 
> Therefore, can you provide the complete evaluation results or guide us on how to adjust configuration file to get correct results.
> 
> Thx so much



> Hello, the paper shows the results of the RGB-D SLAM on the Replica datasets. However, I obtained Monocular SLAM tracking results by adjusting the configuration file. For example, on room0 it's about **4cm**, I don't know where I went wrong and the result is unexpected.
> 
> Therefore, can you provide the complete evaluation results or guide us on how to adjust configuration file to get correct results.
> 
> Thx so much
Hi, can you tell me what configuration parameters you have adjusted?

**Comment by suvzzc** [comment]
> Hello, the paper shows the results of the RGB-D SLAM on the Replica datasets. However, I obtained Monocular SLAM tracking results by adjusting the configuration file. For example, on room0 it's about **4cm**, I don't know where I went wrong and the result is unexpected.
> 
> Therefore, can you provide the complete evaluation results or guide us on how to adjust configuration file to get correct results.
> 
> Thx so much
Hi, can you tell me what configuration parameters you have adjusted?
