### ISSUE TITLE
Visualization of novel views

### ISSUE THREAD

**Issue by abhishek47kashyap** [muskie82/MonoGS#3]
How can I visualize the constructed map/scene from novel viewpoints?

On running `python slam.py --config configs/mono/tum/fr3_office.yaml`, the `results` directory has `.ply` files but I'm not seeing the Gaussians themselves that represent the scene being stored anywhere.

**Comment by rmurai0610** [comment]
Hi, the ply file should store the reconstructed Gaussians, and you can verify this by dragging and dropping the ply file into this website
https://antimatter15.com/splat/

Please let us know if this doesn't work.

**Comment by abhishek47kashyap** [comment]
Thanks, dropping the ply file into that website does the job!
