### ISSUE TITLE
How to visialize pointcloud using GUI after training

### ISSUE THREAD

**Issue by Viki1314** [muskie82/MonoGS#30]
Hello! Thanks for your great work.

I wonder how to use GUI to visialize using the GUI you design.
I have the result-----point_cloud.ply file of the fr3_desk scene.

Trank you very much.

**Comment by muskie82** [comment]
Hi, thanks for your interest in our work.

So far, GUI is just for online reconstruction.
To visualise the result, please use some other viewer tools following the issue #3

We plan to release the GUI for offline visualisation later. Indeed we have the GUI for offline inspection during development, but it requires some refactoring to be compatible with this open-source version of the codebase.

Thanks,

**Comment by Viki1314** [comment]
yes,I saw this issue. Thank for your reply!
