### ISSUE TITLE
How the input video is initialized as 3D gaussians?

### ISSUE THREAD

**Issue by Yoona12** [muskie82/MonoGS#45]
I am sorry to bother you again.
As the paper mentions, the original 3DGS algorithm initializes the system by using Colmap to changes the input video/images into sparse point-cloud and then initialize the point-cloud into 3D gaussians.
![image](https://github.com/muskie82/MonoGS/assets/74137557/4b0dbb06-4cd1-4d65-aaa9-8979b5d67a55)the picture is from 《3D Gaussian Splatting for Real-Time Radiance Field Rendering》
But when I read the code, I didn't find the process of converting the input video(RGB/RGB-D) to sparse point-cloud.
Without sparse point-cloud from Colmap, How can you initialize the input video(RGB/RGB-D) into 3D gaussians?
So, I am confused about how the input is initialized as 3D gaussians?
Thanks!

**Comment by rmurai0610** [comment]
We initialise the Gaussians by random initialisation in the monocular case or using depth image in the RGBD case. These are detailed in our paper:
![Screenshot from 2024-04-03 19-06-55](https://github.com/muskie82/MonoGS/assets/17733641/81b3c595-eeac-48ab-88c4-2911075ec046)

The corresponding code is here: https://github.com/muskie82/MonoGS/blob/main/utils/slam_frontend.py#L57-L108
