### ISSUE TITLE
Issue on pip install submodules/simple-knn

### ISSUE THREAD

**Issue by EricXuziang** [muskie82/MonoGS#49]
When I try to install the package simple-knn, it shows blow.

Processing ./submodules/simple-knn
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: simple-knn
  Building wheel for simple-knn (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      running bdist_wheel
      /well/rittscher/users/ycr745/.conda/envs/MonoGS/lib/python3.11/site-packages/torch/utils/cpp_extension.py:500: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_ext
      /well/rittscher/users/ycr745/.conda/envs/MonoGS/lib/python3.11/site-packages/torch/utils/cpp_extension.py:388: UserWarning:
      
                                     !! WARNING !!
      
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      Your compiler (g++ 4.8.5) may be ABI-incompatible with PyTorch!
      Please use a compiler that is ABI-compatible with GCC 5.0 and above.
      See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.
      
      See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
      for instructions on how to install GCC 5 or higher.
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      
                                    !! WARNING !!
      
        warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
      /well/rittscher/users/ycr745/.conda/envs/MonoGS/lib/python3.11/site-packages/torch/utils/cpp_extension.py:425: UserWarning: There are no g++ version bounds defined for CUDA version 12.1
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'simple_knn._C' extension
      creating build
      creating build/temp.linux-x86_64-cpython-311
      gcc -pthread -B /well/rittscher/users/ycr745/.conda/envs/MonoGS/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /well/rittscher/users/ycr745/.conda/envs/MonoGS/include -fPIC -O2 -isystem /well/rittscher/users/ycr745/.conda/envs/MonoGS/include -fPIC -I/well/rittscher/users/ycr745/.conda/envs/MonoGS/lib/python3.11/site-packages/torch/include -I/well/rittscher/users/ycr745/.conda/envs/MonoGS/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/well/rittscher/users/ycr745/.conda/envs/MonoGS/lib/python3.11/site-packages/torch/include/TH -I/well/rittscher/users/ycr745/.conda/envs/MonoGS/lib/python3.11/site-packages/torch/include/THC -I/usr/local/cuda/include -I/well/rittscher/users/ycr745/.conda/envs/MonoGS/include/python3.11 -c ext.cpp -o build/temp.linux-x86_64-cpython-311/ext.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
      gcc: error: unrecognized command line option '-std=c++17'
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simple-knn
  Running setup.py clean for simple-knn
Failed to build simple-knn
ERROR: Could not build wheels for simple-knn, which is required to install pyproject.toml-based projects

Does anyone know what's the problem?

**Comment by muskie82** [comment]
Hi,

I don't have an immediate answer... But for issues related to simple-knn installation, you're more likely to find relevant bug reports in the original 3D Gaussian Splatting repository.
