### ISSUE TITLE
code

### ISSUE THREAD

**Issue by YIXIN-M** [muskie82/MonoGS#53]
”Second, we introduce a novel Gaussian shape regularisation to ensure geometric consistency, which we have found is important for incremental reconstruction. “  This is a sentence from the article, where is this sentence reflected in the code?

**Comment by rmurai0610** [comment]
The line refers to our isotropic regularisation, which is used for mapping.
https://github.com/muskie82/MonoGS/blob/37cebb4b8df24777980eac00276c07059b94762c/utils/slam_backend.py#L230-L231

**Comment by YIXIN-M** [comment]
Thank you！
