### ISSUE TITLE
About render function

### ISSUE THREAD

**Issue by z157181773** [muskie82/MonoGS#55]
Hello! In the process of reading the code, I have some questions and I hope to ask you for advice.
In the code of guassian_renderer.py, the function render uses the parameter mask, but I did not see any mask parameter added where the render function is called. For example: in the front-end and back-end code, the recurring code segment:
render_pkg = render(viewpoint, self.gaussians, self.pipeline_params, self.background)
There is no mask in it.
I would like to ask, what is the function of mask? And where is it used?

**Comment by rmurai0610** [comment]
Hi, these are some debug codes which we forgot to delete.
We prevent the rendering of the non-masked Gaussians:
https://github.com/muskie82/MonoGS/blob/main/gaussian_splatting/gaussian_renderer/__init__.py#L116-L127

but it is not used in our actual system
