### ISSUE TITLE
Visualizing 3D Gaussians

### ISSUE THREAD

**Issue by robofar** [muskie82/MonoGS#57]
How can I visualize 3D Gaussians themselves like in your paper image?
![image](https://github.com/muskie82/MonoGS/assets/160677050/06d6a452-8617-4f06-b8af-b656a41f2988)

**Comment by muskie82** [comment]
Hi, 
just try out Elipsoid Shader checkbox in our GUI.

**Comment by TommasoLabieni** [comment]
Hello @muskie82, I checked the Elipsoid Shader in the GUI as you can see here:

![Screenshot from 2024-07-26 16-15-47](https://github.com/user-attachments/assets/d3c5ccdd-c7b1-4fd0-b0dd-e7d9da9f1342)

but I still cannot visualize 3D Gaussians... do you have any idea why this happens? Thanks!

**Comment by taehun-ryu** [comment]
Hello @TommasoLabieni, I have same issue with you. Did you solve it?
