### ISSUE TITLE
Testing MonoGS on fisheye images

### ISSUE THREAD

**Issue by phongnhhn92** [muskie82/MonoGS#58]
Hi,

Thanks for the code ! I have managed to run the code on the provided code and I am wondering if the method can work on fisheye images (self-driving scenario) such as [Woodscape](https://github.com/valeoai/WoodScape). 

I wonder if the current method can handle dynamic objects and multi-view settings of self-driving data.

**Comment by muskie82** [comment]
Hi,

Thanks for trying our code.

The code only supports pinhole camera model, so definitely need some sort of image rectification based on the fisheye camera model.
The code does not have any dynamic object masking and it should be difficult to run it on autonomous driving dataset as-is... this could be one research topic.
