### ISSUE TITLE
Question about rendering hole

### ISSUE THREAD

**Issue by Buffyqsf** [muskie82/MonoGS#60]
I got a hole in my own captured data as below, I've tried to find out the reason but failed.
![image](https://github.com/muskie82/MonoGS/assets/89965829/ba6fdf16-62a9-4ba1-9a47-fbb754843f74)
And I found there is Gaussian, because when I change the view camera's z position, the hole dispeared like below.
Wondering if you have any experience in such situation.
![image](https://github.com/muskie82/MonoGS/assets/89965829/2fb78872-1e5e-488c-adb1-bbe4dbf26d54)

**Comment by Buffyqsf** [comment]
I found there seems to have a crop depth min(near 0.2), but I can't find any code can change this(I've tried to adjust near and far or fov in my view camera)

**Comment by rmurai0610** [comment]
Can you try editing this line?
https://github.com/rmurai0610/diff-gaussian-rasterization-w-pose/blob/main/cuda_rasterizer/auxiliary.h#L154
You'll need to re-compile the diff-gaussian using
pip install -e submodules/diff-gaussian-rasterization

**Comment by Buffyqsf** [comment]
well, it seems to be the line! Thank you very much! And I'll try it later.

**Comment by Buffyqsf** [comment]
I've tried but I still got the problem, it should be this line of code, but I don't know why it doesn't work. I've tried to bypass this by setting a unreal depth scale haha. Anyway thanks for your help!
