### ISSUE TITLE
Question about traj.txt in Replica Dataset

### ISSUE THREAD

**Issue by TimChenyu** [muskie82/MonoGS#61]
I might be missing the most obvious, but does anyone know what the values represent in traj.txt in the replica dataset? 

Thanks thanks

**Comment by muskie82** [comment]
Hi,
I think it represents 4*4 camera transformation matrices associated to the frame.

Best,

**Comment by TimChenyu** [comment]
Thanks!
I figured it out but forgot to close this. Here is a link that helped me transform the associated values from other dataformats:
https://www.mathworks.com/help/nav/ref/se3.html

Best,
Tim
