### ISSUE TITLE
get_loss mapping

### ISSUE THREAD

**Issue by z157181773** [muskie82/MonoGS#63]
Loss mapping+=get_loss mapping（

Self. config, image, depth, viewpoint, capacity

）

I saw this code in the backend, which calculates the loss. What is the difference between this and the loss calculation of Guassian plating: loss=(1.0- opt. lambda_dssim) * Ll1+opt. lambda_dssim * (1.0- ssim (image, gt_image))?

I saw the code for get_loss_mapping, which is divided into RGB and RBGD calculations, but I cannot distinguish the difference between the two

**Comment by muskie82** [comment]
Hi,
We are not using ssim loss for tracking/mapping.
get_loss_mapping_rgbd uses depth supervision, while get_loss_mapping_rgb does not.

Best,
