### ISSUE TITLE
Jacobian determinant of the camera pose

### ISSUE THREAD

**Issue by Carloslius** [muskie82/MonoGS#68]
What part of the code is the calculation of the explicit Jacobian determinant of the camera pose?

**Comment by muskie82** [comment]
Hi,
Please checkout our [diff-gaussian-rasterization-w-pose](https://github.com/rmurai0610/diff-gaussian-rasterization-w-pose/).
[This commit log](https://github.com/rmurai0610/diff-gaussian-rasterization-w-pose/commit/8fa512eae9228d08d88058c588caf25032b7d142) might be useful to see the difference from the original rasterizer.
