### ISSUE TITLE
Densification methods confusion

### ISSUE THREAD

**Issue by robofar** [muskie82/MonoGS#69]
Hello. I have doubt regarding method `densification_postfix` and `cat_tensors_to_optimizer`. So, in method `densification_postfix`, `cat_tensors_to_optimizer` is called to (I guess) append new Gaussians to current list of Gaussians. Can someone explain method `cat_tensors_to_optimizer` in more details, because I cannot understand it properly?

**Comment by muskie82** [comment]
Hi,
It is the same as in the original [3DGS](https://github.com/graphdeco-inria/gaussian-splatting/blob/472689c0dc70417448fb451bf529ae532d32c095/scene/gaussian_model.py#L307).
Basically cat_tensors_to_optimizer adds the tensor newly registered by the densification to the variables in the optimizer.

Best,
