### ISSUE TITLE
How to run in a single 3090?

### ISSUE THREAD

**Issue by bobfacer** [muskie82/MonoGS#7]
It seems that the config of replica can not run in a single 3090 due to cuda out of memory,which parameter can be changed to run in a single 3090 with 24GiB memory total?

**Comment by rmurai0610** [comment]
Hi, it should work on the replica with 3090 (we tested with 4090 and it has 24GiB too)
Can you let us know which replica sequence you are running?

Make sure that only MonoGS is running on your GPU (i.e. no other resource-intensive process running on the same GPU), and if it still doesn't work, you can try on eval mode (no GUI) and see if it runs out of memory.
