### ISSUE TITLE
Window of keyframes and last keyframe possible mistake

### ISSUE THREAD

**Issue by robofar** [muskie82/MonoGS#70]
Hello. I am looking at your `frontend.py` and I found one line that confuses me (maybe it is mistake I am not sure):
`last_keyframe_idx = self.current_window[0]`

[code line](https://github.com/muskie82/MonoGS/blob/main/utils/slam_frontend.py#L412)

As I can see from the code, `current_window` refers to the current window of keyframes. I am doubting why you use index `0`, maybe you want index `-1` for last keyframe in current window?

**Comment by rmurai0610** [comment]
Hi 
The last keyframe refers to the most recent keyframe, not the oldest keyframe in the buffer.
I hope this clarifies your question!

**Comment by robofar** [comment]
Yes, but oldest keyframe in buffer should be at position 0 right? Last keyframe added should be at last position (i.e -1 position) I guess .. ? I mean as I see you are just appending it so that's why I asked

**Comment by rmurai0610** [comment]
Ah I see, we append to the front for the window
https://github.com/muskie82/MonoGS/blob/main/utils/slam_frontend.py#L231
Hope this helps!

**Comment by robofar** [comment]
Thanks for the clarification!
