### ISSUE TITLE
RuntimeError: numel: integer multiplication overflow

### ISSUE THREAD

**Issue by zhongyingji** [muskie82/MonoGS#71]
Hi, thanks for the great work! 

I use your implemented package of diff-gaussian-rasterization, and I directly replace the rasterization package of original 3DGS with yours. 

Then I modify two parts as followings to meet input requirements of your code, 

<img width="368" alt="Screen Shot 2024-04-16 at 20 42 28" src="https://github.com/muskie82/MonoGS/assets/33337824/e37157b6-3bd0-4b88-9251-ca9dbfde848a">

<img width="462" alt="Screen Shot 2024-04-16 at 20 42 43" src="https://github.com/muskie82/MonoGS/assets/33337824/4968c34f-8239-4407-8635-89fb7ef0f2dc">

And I got the error of "integer multiplication overflow": 

<img width="975" alt="Screen Shot 2024-04-16 at 20 45 21" src="https://github.com/muskie82/MonoGS/assets/33337824/f4361888-e7ac-4ba1-a597-8a0be9a84dd4">

I tried to run with `CUDA-LAUNCHBLOCKING=1 python xxx", but the error kept the same. Do you have any idea on locating the error?

Thank you.

**Comment by muskie82** [comment]
Thank you for your interest in our work.

Hmm... I never seen this before. Just to check, is the type of `viewpoint_camera.projection_matrix` torch.float32?

**Comment by zhongyingji** [comment]
I solved in by https://github.com/graphdeco-inria/gaussian-splatting/issues/41. 

Thank you.
