### ISSUE TITLE
About the initialization of Gaussian

### ISSUE THREAD

**Issue by leqwq103** [muskie82/MonoGS#73]
Hello, I have some questions about the initialization of Gaussian:
Regarding the original Gaussian scattering, the original density small variance (DSV) random initialization was used, where the initial number of Gaussian N was set to N>100K. I can't find the initialization for this part in MonoGS, which means I can't find the code for initializing Gaussian points at the beginning.

**Comment by leqwq103** [comment]
It should correspond to the dataset readers. py in the Gaussian spacing code, but I cannot find the corresponding code in MonoGS

**Comment by muskie82** [comment]
Hi,
Checkout #45 .

Best,
