### ISSUE TITLE
Question on the derivation of Jacobians

### ISSUE THREAD

**Issue by Yoona12** [muskie82/MonoGS#75]
Thanks for your great work!
In the **3.2 Camera Pose Optimisation**, There is the derivation of Jacobians in Eq.(3)-(6).  
![image](https://github.com/muskie82/MonoGS/assets/74137557/b0e250f3-ff2b-4f6a-bb2b-22f369f514d3)
But, when i read the code, i found  that no codes were found corresponding to these formulas in the code. 
And I guess that Eq.(3)-(6) corresponds to https://github.com/muskie82/MonoGS/blob/main/utils/slam_frontend.py#L162-L193 ,but i am not sure.
So, I am confused about the purpose of  derivating these formulas  and i want to  which part of codes corresponds to Eq.(3)-(6).
Looking for your reply! Thanks

**Comment by muskie82** [comment]
Hi,
Please checkout #68.
Best,
