### ISSUE TITLE
Conda env buildin error - ERROR: Directory 'submodules/simple-knn' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

### ISSUE THREAD

**Issue by Dreambyland** [muskie82/MonoGS#8]
While building conda env  simple-knn packages is not found. Does anyone face this problem? pip install simple_knn does not help at all.

**Comment by Eku127** [comment]
clone the repo with '--recursive'

**Comment by muskie82** [comment]
As @Eku127 suggests, please check if you cloned submodules correctly.
`git submodule update --init --recursive` in your current dir should also work.
