### ISSUE TITLE
Compared to Original Implementaiton

### ISSUE THREAD

**Issue by TwiceMao** [muskie82/MonoGS#83]
@muskie82 @rmurai0610 @alik-git @DapengFeng @Muhammad0312   Thank you for your excellent work. I want to ask, compared with the original rendering code, will it take up much more GPU memory? If so, approximately how much?

**Comment by muskie82** [comment]
Hi,
Thank you for your interest in our work.
I didn't see any significant difference of GPU memory usage for the forward/backward rendering.
